- name: Set hostname for management node
  hostname:
    name: "RKE2-SUSE-MANAGEMENT-NODE-01"

- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.33.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Copy kubeconfig from first master node to management node
  fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /tmp/kubeconfig_{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Place kubeconfig in ~/.kube/config
  copy:
    src: /tmp/kubeconfig_{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Update kubeconfig to use master node IP instead of localhost
  replace:
    path: /root/.kube/config
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}:9345"
