- name: Set hostname for AGENTS node
  hostname:
    name: "RKE2-SUSE-AGENT-{{ '%02d' | format(play_hosts.index(inventory_hostname) + 1) }}"

- name: Download RKE2 install script
  get_url:
    url: https://get.rke2.io
    dest: /root/install.sh
    mode: '0755'

- name: Install RKE2 AGENT
  shell: INSTALL_RKE2_TYPE=agent ./install.sh
  args:
    chdir: /root

- name: Create RKE2 config directory
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Gather facts from MASTER nodes
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['masters'] }}"

- name: Generate RKE2 AGENT config.yaml
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      server: https://{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}:9345
      token: {{ hostvars[groups['masters'][0]].node_token }}
      cni: canal

- name: Enable and start rke2-agent service
  systemd:
    name: rke2-agent
    enabled: yes
    state: started
