- name: Reboot all managed hosts immediately
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Reboot the host now
      reboot:
        msg: "Immediate reboot by Ansible"
        pre_reboot_delay: 0
        reboot_timeout: 600
